services:
  - type: web
    name: crypto-tracker
    env: docker
    plan: free
    buildCommand: ""
    startCommand: julia -e "using Genie; Genie.loadapp(); Genie.up(8000, host=\"0.0.0.0\")"
    dockerfilePath: Dockerfile
